"""Added team column

Revision ID: 6bf5cdcac832
Revises: 
Create Date: 2026-08-31 15:22:04.945114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf5cdcac832'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport_record', schema=None) as batch_op:
        batch_op.drop_column('team')

    # ### end Alembic commands ###
