"""Added school and team to SportRecord

Revision ID: b2747048474a
Revises: 6bf5cdcac832
Create Date: 2026-08-31 15:53:52.168693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2747048474a'
down_revision = '6bf5cdcac832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport_record', schema=None) as batch_op:
        batch_op.drop_column('school')

    # ### end Alembic commands ###
